n = int(input())
for i in range(n):print('@'*n*3+' '*n*1+'@'*n*1)
for i in range(n):print('@'*n*1+' '*n*1+'@'*n*1+' '*n*1+'@'*n*1)
for i in range(n):print('@'*n*1+' '*n*1+'@'*n*1+' '*n*1+'@'*n*1)
for i in range(n):print('@'*n*1+' '*n*1+'@'*n*1+' '*n*1+'@'*n*1)
for i in range(n):print('@'*n*1+' '*n*1+'@'*n*3)